Search.appendIndex(
    [
                {
            "fqsen": "\\IronCore\\BatchEncryptedDocuments",
            "name": "BatchEncryptedDocuments",
            "summary": "A\u0020batch\u0020of\u0020documents\u0020which\u0020have\u0020been\u0020encrypted.",
            "url": "classes/IronCore-BatchEncryptedDocuments.html"
        },                {
            "fqsen": "\\IronCore\\BatchEncryptedDocuments\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-BatchEncryptedDocuments.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\BatchEncryptedDocuments\u003A\u003AgetEncryptedDocuments\u0028\u0029",
            "name": "getEncryptedDocuments",
            "summary": "",
            "url": "classes/IronCore-BatchEncryptedDocuments.html#method_getEncryptedDocuments"
        },                {
            "fqsen": "\\IronCore\\BatchEncryptedDocuments\u003A\u003AgetFailures\u0028\u0029",
            "name": "getFailures",
            "summary": "",
            "url": "classes/IronCore-BatchEncryptedDocuments.html#method_getFailures"
        },                {
            "fqsen": "\\IronCore\\BatchEncryptedDocuments\u003A\u003A\u0024documents",
            "name": "documents",
            "summary": "",
            "url": "classes/IronCore-BatchEncryptedDocuments.html#property_documents"
        },                {
            "fqsen": "\\IronCore\\BatchEncryptedDocuments\u003A\u003A\u0024failures",
            "name": "failures",
            "summary": "",
            "url": "classes/IronCore-BatchEncryptedDocuments.html#property_failures"
        },                {
            "fqsen": "\\IronCore\\BatchPlaintextDocuments",
            "name": "BatchPlaintextDocuments",
            "summary": "A\u0020batch\u0020of\u0020documents\u0020which\u0020have\u0020been\u0020decrypted.",
            "url": "classes/IronCore-BatchPlaintextDocuments.html"
        },                {
            "fqsen": "\\IronCore\\BatchPlaintextDocuments\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-BatchPlaintextDocuments.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\BatchPlaintextDocuments\u003A\u003AgetPlaintextDocuments\u0028\u0029",
            "name": "getPlaintextDocuments",
            "summary": "",
            "url": "classes/IronCore-BatchPlaintextDocuments.html#method_getPlaintextDocuments"
        },                {
            "fqsen": "\\IronCore\\BatchPlaintextDocuments\u003A\u003AgetFailures\u0028\u0029",
            "name": "getFailures",
            "summary": "",
            "url": "classes/IronCore-BatchPlaintextDocuments.html#method_getFailures"
        },                {
            "fqsen": "\\IronCore\\BatchPlaintextDocuments\u003A\u003A\u0024documents",
            "name": "documents",
            "summary": "",
            "url": "classes/IronCore-BatchPlaintextDocuments.html#property_documents"
        },                {
            "fqsen": "\\IronCore\\BatchPlaintextDocuments\u003A\u003A\u0024failures",
            "name": "failures",
            "summary": "",
            "url": "classes/IronCore-BatchPlaintextDocuments.html#property_failures"
        },                {
            "fqsen": "\\IronCore\\Bytes",
            "name": "Bytes",
            "summary": "Wrapper\u0020around\u0020a\u0020string\u0020that\u0020contains\u0020raw\u0020bytes",
            "url": "classes/IronCore-Bytes.html"
        },                {
            "fqsen": "\\IronCore\\Bytes\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-Bytes.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\Bytes\u003A\u003AfromBase64\u0028\u0029",
            "name": "fromBase64",
            "summary": "Constructs\u0020Bytes\u0020from\u0020a\u0020base64\u002Dencoded\u0020string.\u0020Holds\u0020the\u0020decoded\u0020bytes.\u0020If\u0020the\u0020input\nis\u0020not\u0020valid\u0020base64\u0020an\u0020InvalidArgumentException\u0020will\u0020be\u0020thrown.",
            "url": "classes/IronCore-Bytes.html#method_fromBase64"
        },                {
            "fqsen": "\\IronCore\\Bytes\u003A\u003AgetBase64String\u0028\u0029",
            "name": "getBase64String",
            "summary": "Gets\u0020the\u0020base64\u002Dencoded\u0020representation\u0020of\u0020the\u0020held\u0020bytes.",
            "url": "classes/IronCore-Bytes.html#method_getBase64String"
        },                {
            "fqsen": "\\IronCore\\Bytes\u003A\u003AgetHexString\u0028\u0029",
            "name": "getHexString",
            "summary": "Printable\u0020hex\u0020representation\u0020of\u0020the\u0020held\u0020bytes.\u0020To\u0020return\u0020the\u0020held\u0020bytes\nthemselves,\u0020use\u0020\u0060getByteString\u0028\u0029\u0060.",
            "url": "classes/IronCore-Bytes.html#method_getHexString"
        },                {
            "fqsen": "\\IronCore\\Bytes\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Printable\u0020hex\u0020representation\u0020of\u0020the\u0020held\u0020bytes.\u0020To\u0020return\u0020the\u0020held\u0020bytes\nthemselves,\u0020use\u0020\u0060getByteString\u0028\u0029\u0060.",
            "url": "classes/IronCore-Bytes.html#method___toString"
        },                {
            "fqsen": "\\IronCore\\Bytes\u003A\u003Alength\u0028\u0029",
            "name": "length",
            "summary": "Gets\u0020the\u0020length\u0020of\u0020the\u0020held\u0020bytes.",
            "url": "classes/IronCore-Bytes.html#method_length"
        },                {
            "fqsen": "\\IronCore\\Bytes\u003A\u003AbyteSlice\u0028\u0029",
            "name": "byteSlice",
            "summary": "Gets\u0020a\u0020slice\u0020of\u0020the\u0020held\u0020bytes.",
            "url": "classes/IronCore-Bytes.html#method_byteSlice"
        },                {
            "fqsen": "\\IronCore\\Bytes\u003A\u003AgetByteString\u0028\u0029",
            "name": "getByteString",
            "summary": "Gets\u0020the\u0020held\u0020byte\u0020string.",
            "url": "classes/IronCore-Bytes.html#method_getByteString"
        },                {
            "fqsen": "\\IronCore\\Bytes\u003A\u003Aconcat\u0028\u0029",
            "name": "concat",
            "summary": "Concatenates\u0020the\u0020held\u0020bytes\u0020with\u0020the\u0020provided\u0020bytes.",
            "url": "classes/IronCore-Bytes.html#method_concat"
        },                {
            "fqsen": "\\IronCore\\Bytes\u003A\u003AgetAtIndex\u0028\u0029",
            "name": "getAtIndex",
            "summary": "Gets\u0020the\u0020byte\u0020at\u0020the\u0020provided\u0020index.",
            "url": "classes/IronCore-Bytes.html#method_getAtIndex"
        },                {
            "fqsen": "\\IronCore\\Bytes\u003A\u003A\u0024bytes",
            "name": "bytes",
            "summary": "",
            "url": "classes/IronCore-Bytes.html#property_bytes"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Aes",
            "name": "Aes",
            "summary": "",
            "url": "classes/IronCore-Crypto-Aes.html"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Aes\u003A\u003AgetCurrentDocumentHeaderVersion\u0028\u0029",
            "name": "getCurrentDocumentHeaderVersion",
            "summary": "Gets\u0020the\u0020current\u0020IronCore\u0020document\u0020header\u0020version\u0020as\u0020a\u0020single\u0020byte.",
            "url": "classes/IronCore-Crypto-Aes.html#method_getCurrentDocumentHeaderVersion"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Aes\u003A\u003AgetDocumentMagic\u0028\u0029",
            "name": "getDocumentMagic",
            "summary": "Gets\u0020IronCore\u0020document\u0020magic\u0020bytes\u0020that\u0020are\u0020included\u0020in\u0020every\u0020document\u0027s\u0020preamble",
            "url": "classes/IronCore-Crypto-Aes.html#method_getDocumentMagic"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Aes\u003A\u003Aencrypt\u0028\u0029",
            "name": "encrypt",
            "summary": "Encrypts\u0020given\u0020plaintext\u0020with\u0020the\u0020provided\u0020key.",
            "url": "classes/IronCore-Crypto-Aes.html#method_encrypt"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Aes\u003A\u003AencryptWithIv\u0028\u0029",
            "name": "encryptWithIv",
            "summary": "Encrypts\u0020given\u0020plaintext\u0020with\u0020the\u0020provided\u0020key\u0020and\u0020IV.",
            "url": "classes/IronCore-Crypto-Aes.html#method_encryptWithIv"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Aes\u003A\u003Adecrypt\u0028\u0029",
            "name": "decrypt",
            "summary": "Takes\u0020a\u0020string\u0020of\u0020arbitrary\u0020bytes\u0020and\u0020decrypts\u0020it\u0020using\u0020a\u0020given\u0020key.",
            "url": "classes/IronCore-Crypto-Aes.html#method_decrypt"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Aes\u003A\u003AencryptDocument\u0028\u0029",
            "name": "encryptDocument",
            "summary": "Encrypts\u0020a\u0020document.",
            "url": "classes/IronCore-Crypto-Aes.html#method_encryptDocument"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Aes\u003A\u003AdecryptDocument\u0028\u0029",
            "name": "decryptDocument",
            "summary": "Decrypts\u0020an\u0020encrypted\u0020document.",
            "url": "classes/IronCore-Crypto-Aes.html#method_decryptDocument"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Aes\u003A\u003AsplitDocument\u0028\u0029",
            "name": "splitDocument",
            "summary": "Splits\u0020an\u0020IronCore\u0020encrypted\u0020document\u0020into\u0020its\u0020component\u0020pieces.",
            "url": "classes/IronCore-Crypto-Aes.html#method_splitDocument"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Aes\u003A\u003AverifyPreamble\u0028\u0029",
            "name": "verifyPreamble",
            "summary": "Verifies\u0020that\u0020the\u0020preamble\u0020is\u0020the\u0020correct\u0020length\u0020and\u0020version,\u0020contains\u0020the\u0020string\u0020\u0022IRON\u0022,\nand\u0020indicates\u0020a\u0020valid\u0020header\u0020length.",
            "url": "classes/IronCore-Crypto-Aes.html#method_verifyPreamble"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Aes\u003A\u003AcontainsIroncoreMagic\u0028\u0029",
            "name": "containsIroncoreMagic",
            "summary": "Verifies\u0020that\u0020bytes\u00202\u002D5\u0020are\u0020the\u0020IronCore\u0020magic\u0020string.",
            "url": "classes/IronCore-Crypto-Aes.html#method_containsIroncoreMagic"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Aes\u003A\u003AgetHeaderSize\u0028\u0029",
            "name": "getHeaderSize",
            "summary": "Converts\u0020bytes\u00206\u0020and\u00207\u0020of\u0020the\u0020fixed\u0020preamble\u0020to\u0020an\u0020integer\u0020that\nrepresents\u0020the\u0020length\u0020of\u0020the\u0020header.",
            "url": "classes/IronCore-Crypto-Aes.html#method_getHeaderSize"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Aes\u003A\u003AgenerateHeader\u0028\u0029",
            "name": "generateHeader",
            "summary": "Generates\u0020a\u0020header\u0020to\u0020mark\u0020the\u0020encrypted\u0020document\u0020as\u0020ours.",
            "url": "classes/IronCore-Crypto-Aes.html#method_generateHeader"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Aes\u003A\u003AcreateHeaderProto\u0028\u0029",
            "name": "createHeaderProto",
            "summary": "Make\u0020a\u0020V3DocumentHeader\u0020with\u0020a\u0020SaaSShieldHeader\u0020and\u0020a\u0020generated\u0020signature.",
            "url": "classes/IronCore-Crypto-Aes.html#method_createHeaderProto"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Aes\u003A\u003AgenerateSignature\u0028\u0029",
            "name": "generateSignature",
            "summary": "Generates\u0020a\u0020signature\u0020over\u0020the\u0020header\u0020using\u0020the\u0020provided\u0020document\u0020encryption\u0020key\u0020and\u0020IV.",
            "url": "classes/IronCore-Crypto-Aes.html#method_generateSignature"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Aes\u003A\u003AverifySignature\u0028\u0029",
            "name": "verifySignature",
            "summary": "Verifies\u0020a\u0020document\u0020header\u0027s\u0020signature.",
            "url": "classes/IronCore-Crypto-Aes.html#method_verifySignature"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Aes\u003A\u003AIV_LEN",
            "name": "IV_LEN",
            "summary": "",
            "url": "classes/IronCore-Crypto-Aes.html#constant_IV_LEN"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Aes\u003A\u003ATAG_LEN",
            "name": "TAG_LEN",
            "summary": "",
            "url": "classes/IronCore-Crypto-Aes.html#constant_TAG_LEN"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Aes\u003A\u003ADOCUMENT_HEADER_META_LENGTH",
            "name": "DOCUMENT_HEADER_META_LENGTH",
            "summary": "The\u0020size\u0020of\u0020the\u0020fixed\u0020length\u0020portion\u0020of\u0020the\u0020header\u0020\u0028version,\u0020magic,\u0020size\u0029",
            "url": "classes/IronCore-Crypto-Aes.html#constant_DOCUMENT_HEADER_META_LENGTH"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Aes\u003A\u003AMAX_HEADER_SIZE",
            "name": "MAX_HEADER_SIZE",
            "summary": "Max\u0020IronCore\u0020header\u0020size.\u0020Equals\u0020256\u0020\u002A\u0020255\u0020\u002B\u0020255\u0020since\u0020we\u0020do\u0020a\u00202\u0020byte\u0020size.",
            "url": "classes/IronCore-Crypto-Aes.html#constant_MAX_HEADER_SIZE"
        },                {
            "fqsen": "\\IronCore\\Crypto\\CryptoRng",
            "name": "CryptoRng",
            "summary": "Cryptographically\u002Dsecure\u0020random\u0020number\u0020generator",
            "url": "classes/IronCore-Crypto-CryptoRng.html"
        },                {
            "fqsen": "\\IronCore\\Crypto\\CryptoRng\u003A\u003ArandomBytes\u0028\u0029",
            "name": "randomBytes",
            "summary": "",
            "url": "classes/IronCore-Crypto-CryptoRng.html#method_randomBytes"
        },                {
            "fqsen": "\\IronCore\\Crypto\\CryptoRng\u003A\u003AgetInstance\u0028\u0029",
            "name": "getInstance",
            "summary": "",
            "url": "classes/IronCore-Crypto-CryptoRng.html#method_getInstance"
        },                {
            "fqsen": "\\IronCore\\Crypto\\CryptoRng\u003A\u003A\u0024instance",
            "name": "instance",
            "summary": "",
            "url": "classes/IronCore-Crypto-CryptoRng.html#property_instance"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Rng",
            "name": "Rng",
            "summary": "",
            "url": "classes/IronCore-Crypto-Rng.html"
        },                {
            "fqsen": "\\IronCore\\Crypto\\Rng\u003A\u003ArandomBytes\u0028\u0029",
            "name": "randomBytes",
            "summary": "",
            "url": "classes/IronCore-Crypto-Rng.html#method_randomBytes"
        },                {
            "fqsen": "\\IronCore\\DocumentParts",
            "name": "DocumentParts",
            "summary": "A\u0020parsed\u0020IronCore\u0020encrypted\u0020document",
            "url": "classes/IronCore-DocumentParts.html"
        },                {
            "fqsen": "\\IronCore\\DocumentParts\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-DocumentParts.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\DocumentParts\u003A\u003AgetPreamble\u0028\u0029",
            "name": "getPreamble",
            "summary": "Gets\u0020the\u0020preamble\u0020of\u0020the\u0020document.",
            "url": "classes/IronCore-DocumentParts.html#method_getPreamble"
        },                {
            "fqsen": "\\IronCore\\DocumentParts\u003A\u003AgetHeader\u0028\u0029",
            "name": "getHeader",
            "summary": "Gets\u0020the\u0020header\u0020of\u0020the\u0020document.",
            "url": "classes/IronCore-DocumentParts.html#method_getHeader"
        },                {
            "fqsen": "\\IronCore\\DocumentParts\u003A\u003AgetCiphertext\u0028\u0029",
            "name": "getCiphertext",
            "summary": "Gets\u0020the\u0020encrypted\u0020payload\u0020of\u0020the\u0020document.",
            "url": "classes/IronCore-DocumentParts.html#method_getCiphertext"
        },                {
            "fqsen": "\\IronCore\\DocumentParts\u003A\u003A\u0024preamble",
            "name": "preamble",
            "summary": "",
            "url": "classes/IronCore-DocumentParts.html#property_preamble"
        },                {
            "fqsen": "\\IronCore\\DocumentParts\u003A\u003A\u0024header",
            "name": "header",
            "summary": "",
            "url": "classes/IronCore-DocumentParts.html#property_header"
        },                {
            "fqsen": "\\IronCore\\DocumentParts\u003A\u003A\u0024ciphertext",
            "name": "ciphertext",
            "summary": "",
            "url": "classes/IronCore-DocumentParts.html#property_ciphertext"
        },                {
            "fqsen": "\\IronCore\\EncryptedDocument",
            "name": "EncryptedDocument",
            "summary": "A\u0020set\u0020of\u0020fields\u0020which\u0020has\u0020been\u0020encrypted.",
            "url": "classes/IronCore-EncryptedDocument.html"
        },                {
            "fqsen": "\\IronCore\\EncryptedDocument\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-EncryptedDocument.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\EncryptedDocument\u003A\u003AgetEncryptedFields\u0028\u0029",
            "name": "getEncryptedFields",
            "summary": "",
            "url": "classes/IronCore-EncryptedDocument.html#method_getEncryptedFields"
        },                {
            "fqsen": "\\IronCore\\EncryptedDocument\u003A\u003AgetEdek\u0028\u0029",
            "name": "getEdek",
            "summary": "",
            "url": "classes/IronCore-EncryptedDocument.html#method_getEdek"
        },                {
            "fqsen": "\\IronCore\\EncryptedDocument\u003A\u003A\u0024encryptedFields",
            "name": "encryptedFields",
            "summary": "",
            "url": "classes/IronCore-EncryptedDocument.html#property_encryptedFields"
        },                {
            "fqsen": "\\IronCore\\EncryptedDocument\u003A\u003A\u0024edek",
            "name": "edek",
            "summary": "",
            "url": "classes/IronCore-EncryptedDocument.html#property_edek"
        },                {
            "fqsen": "\\IronCore\\EventMetadata",
            "name": "EventMetadata",
            "summary": "RequestMetadata\u0020with\u0020an\u0020optional\u0020\u0060timestampMillis\u0060\u0020referencing\u0020when\u0020a\u0020security\u0020event\u0020took\u0020place.",
            "url": "classes/IronCore-EventMetadata.html"
        },                {
            "fqsen": "\\IronCore\\EventMetadata\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-EventMetadata.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\EventMetadata\u003A\u003AgetTimestampMillis\u0028\u0029",
            "name": "getTimestampMillis",
            "summary": "Gets\u0020the\u0020timestampMillis.",
            "url": "classes/IronCore-EventMetadata.html#method_getTimestampMillis"
        },                {
            "fqsen": "\\IronCore\\EventMetadata\u003A\u003AgetPostData\u0028\u0029",
            "name": "getPostData",
            "summary": "Gets\u0020an\u0020associative\u0020array\u0020of\u0020data\u0020that\u0020can\u0020be\u0020serialized\nand\u0020sent\u0020to\u0020the\u0020Tenant\u0020Security\u0020Proxy.",
            "url": "classes/IronCore-EventMetadata.html#method_getPostData"
        },                {
            "fqsen": "\\IronCore\\EventMetadata\u003A\u003A\u0024timestampMillis",
            "name": "timestampMillis",
            "summary": "",
            "url": "classes/IronCore-EventMetadata.html#property_timestampMillis"
        },                {
            "fqsen": "\\IronCore\\Exception\\CryptoException",
            "name": "CryptoException",
            "summary": "This\u0020exception\u0020indicates\u0020a\u0020problem\u0020with\u0020encrypting,\u0020decrypting\u0020or\u0020verifying\u0020signatures.",
            "url": "classes/IronCore-Exception-CryptoException.html"
        },                {
            "fqsen": "\\IronCore\\Exception\\KmsException",
            "name": "KmsException",
            "summary": "This\u0020exception\u0020indicates\u0020a\u0020problem\u0020with\u0020the\u0020Tenant\u0020Security\u0020Proxy\u0020talking\u0020to\u0020the\nKMS,\u0020or\u0020a\u0020problem\u0020with\u0020KMS\u0020keys.",
            "url": "classes/IronCore-Exception-KmsException.html"
        },                {
            "fqsen": "\\IronCore\\Exception\\SecurityEventException",
            "name": "SecurityEventException",
            "summary": "This\u0020indicates\u0020a\u0020problem\u0020with\u0020logging\u0020a\u0020security\u0020event\u0020to\u0020the\u0020TSP.",
            "url": "classes/IronCore-Exception-SecurityEventException.html"
        },                {
            "fqsen": "\\IronCore\\Exception\\TenantSecurityException",
            "name": "TenantSecurityException",
            "summary": "This\u0020exception\u0020indicates\u0020a\u0020problem\u0020talking\u0020to\u0020the\u0020TSP\u0020or\u0020the\u0020TSP\u0020talking\u0020to\u0020the\nkey\u0020management\u0020servers.\u0020See\u0020the\u0020fromResponse\u0020static\u0020function\u0020for\u0020the\u0020code\u0020\u002D\u003E\u0020exception\u0020mapping.",
            "url": "classes/IronCore-Exception-TenantSecurityException.html"
        },                {
            "fqsen": "\\IronCore\\Exception\\TenantSecurityException\u003A\u003AfromDecodedJson\u0028\u0029",
            "name": "fromDecodedJson",
            "summary": "Converts\u0020from\u0020a\u0020JSON\u002Ddecoded\u0020TSP\u0020error\u0020response\u0020to\u0020a\u0020TenantSecurityException.",
            "url": "classes/IronCore-Exception-TenantSecurityException.html#method_fromDecodedJson"
        },                {
            "fqsen": "\\IronCore\\Exception\\TenantSecurityException\u003A\u003AfromResponse\u0028\u0029",
            "name": "fromResponse",
            "summary": "Converts\u0020from\u0020a\u0020TSP\u0020error\u0020response\u0020to\u0020a\u0020TenantSecurityException.",
            "url": "classes/IronCore-Exception-TenantSecurityException.html#method_fromResponse"
        },                {
            "fqsen": "\\IronCore\\Exception\\TspServiceException",
            "name": "TspServiceException",
            "summary": "This\u0020indicates\u0020a\u0020problem\u0020from\u0020the\u0020Tenant\u0020Security\u0020Proxy\u0020itself\u0020\u0028such\u0020as\u0020invalid\u0020API\u0020key\u0029.",
            "url": "classes/IronCore-Exception-TspServiceException.html"
        },                {
            "fqsen": "\\IronCore\\IclFields",
            "name": "IclFields",
            "summary": "Holds\u0020metadata\u0020to\u0020pass\u0020to\u0020the\u0020Tenant\u0020Security\u0020Proxy\u0020for\u0020logging\u0020purposes.",
            "url": "classes/IronCore-IclFields.html"
        },                {
            "fqsen": "\\IronCore\\IclFields\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-IclFields.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\IclFields\u003A\u003A\u0024requestingId",
            "name": "requestingId",
            "summary": "",
            "url": "classes/IronCore-IclFields.html#property_requestingId"
        },                {
            "fqsen": "\\IronCore\\IclFields\u003A\u003A\u0024dataLabel",
            "name": "dataLabel",
            "summary": "",
            "url": "classes/IronCore-IclFields.html#property_dataLabel"
        },                {
            "fqsen": "\\IronCore\\IclFields\u003A\u003A\u0024sourceIp",
            "name": "sourceIp",
            "summary": "",
            "url": "classes/IronCore-IclFields.html#property_sourceIp"
        },                {
            "fqsen": "\\IronCore\\IclFields\u003A\u003A\u0024objectId",
            "name": "objectId",
            "summary": "",
            "url": "classes/IronCore-IclFields.html#property_objectId"
        },                {
            "fqsen": "\\IronCore\\IclFields\u003A\u003A\u0024requestId",
            "name": "requestId",
            "summary": "",
            "url": "classes/IronCore-IclFields.html#property_requestId"
        },                {
            "fqsen": "\\IronCore\\IclFieldsWithEvent",
            "name": "IclFieldsWithEvent",
            "summary": "Holds\u0020the\u0020event\u0020to\u0020pass\u0020to\u0020the\u0020Tenant\u0020Security\u0020Proxy\u0020for\u0020logging\u0020purposes.",
            "url": "classes/IronCore-IclFieldsWithEvent.html"
        },                {
            "fqsen": "\\IronCore\\IclFieldsWithEvent\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-IclFieldsWithEvent.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\IclFieldsWithEvent\u003A\u003A\u0024event",
            "name": "event",
            "summary": "",
            "url": "classes/IronCore-IclFieldsWithEvent.html#property_event"
        },                {
            "fqsen": "\\IronCore\\PlaintextDocument",
            "name": "PlaintextDocument",
            "summary": "A\u0020decrypted\u0020document.",
            "url": "classes/IronCore-PlaintextDocument.html"
        },                {
            "fqsen": "\\IronCore\\PlaintextDocument\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-PlaintextDocument.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\PlaintextDocument\u003A\u003AgetDecryptedFields\u0028\u0029",
            "name": "getDecryptedFields",
            "summary": "",
            "url": "classes/IronCore-PlaintextDocument.html#method_getDecryptedFields"
        },                {
            "fqsen": "\\IronCore\\PlaintextDocument\u003A\u003AgetEdek\u0028\u0029",
            "name": "getEdek",
            "summary": "",
            "url": "classes/IronCore-PlaintextDocument.html#method_getEdek"
        },                {
            "fqsen": "\\IronCore\\PlaintextDocument\u003A\u003A\u0024decryptedFields",
            "name": "decryptedFields",
            "summary": "",
            "url": "classes/IronCore-PlaintextDocument.html#property_decryptedFields"
        },                {
            "fqsen": "\\IronCore\\PlaintextDocument\u003A\u003A\u0024edek",
            "name": "edek",
            "summary": "",
            "url": "classes/IronCore-PlaintextDocument.html#property_edek"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\DataControlPlatformHeader",
            "name": "DataControlPlatformHeader",
            "summary": "Generated\u0020from\u0020protobuf\u0020message\u0020\u003Ccode\u003Eproto.ironcorelabs.cmk.DataControlPlatformHeader\u003C\/code\u003E",
            "url": "classes/Proto-IronCoreLabs-DataControlPlatformHeader.html"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\DataControlPlatformHeader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Proto-IronCoreLabs-DataControlPlatformHeader.html#method___construct"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\DataControlPlatformHeader\u003A\u003AgetDocumentId\u0028\u0029",
            "name": "getDocumentId",
            "summary": "Generated\u0020from\u0020protobuf\u0020field\u0020\u003Ccode\u003Estring\u0020document_id\u0020\u003D\u00201\u003B\u003C\/code\u003E",
            "url": "classes/Proto-IronCoreLabs-DataControlPlatformHeader.html#method_getDocumentId"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\DataControlPlatformHeader\u003A\u003AsetDocumentId\u0028\u0029",
            "name": "setDocumentId",
            "summary": "Generated\u0020from\u0020protobuf\u0020field\u0020\u003Ccode\u003Estring\u0020document_id\u0020\u003D\u00201\u003B\u003C\/code\u003E",
            "url": "classes/Proto-IronCoreLabs-DataControlPlatformHeader.html#method_setDocumentId"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\DataControlPlatformHeader\u003A\u003AgetSegmentId\u0028\u0029",
            "name": "getSegmentId",
            "summary": "Generated\u0020from\u0020protobuf\u0020field\u0020\u003Ccode\u003Euint64\u0020segment_id\u0020\u003D\u00202\u003B\u003C\/code\u003E",
            "url": "classes/Proto-IronCoreLabs-DataControlPlatformHeader.html#method_getSegmentId"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\DataControlPlatformHeader\u003A\u003AsetSegmentId\u0028\u0029",
            "name": "setSegmentId",
            "summary": "Generated\u0020from\u0020protobuf\u0020field\u0020\u003Ccode\u003Euint64\u0020segment_id\u0020\u003D\u00202\u003B\u003C\/code\u003E",
            "url": "classes/Proto-IronCoreLabs-DataControlPlatformHeader.html#method_setSegmentId"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\DataControlPlatformHeader\u003A\u003A\u0024document_id",
            "name": "document_id",
            "summary": "Generated\u0020from\u0020protobuf\u0020field\u0020\u003Ccode\u003Estring\u0020document_id\u0020\u003D\u00201\u003B\u003C\/code\u003E",
            "url": "classes/Proto-IronCoreLabs-DataControlPlatformHeader.html#property_document_id"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\DataControlPlatformHeader\u003A\u003A\u0024segment_id",
            "name": "segment_id",
            "summary": "Generated\u0020from\u0020protobuf\u0020field\u0020\u003Ccode\u003Euint64\u0020segment_id\u0020\u003D\u00202\u003B\u003C\/code\u003E",
            "url": "classes/Proto-IronCoreLabs-DataControlPlatformHeader.html#property_segment_id"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\SaaSShieldHeader",
            "name": "SaaSShieldHeader",
            "summary": "Generated\u0020from\u0020protobuf\u0020message\u0020\u003Ccode\u003Eproto.ironcorelabs.cmk.SaaSShieldHeader\u003C\/code\u003E",
            "url": "classes/Proto-IronCoreLabs-SaaSShieldHeader.html"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\SaaSShieldHeader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Proto-IronCoreLabs-SaaSShieldHeader.html#method___construct"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\SaaSShieldHeader\u003A\u003AgetTenantId\u0028\u0029",
            "name": "getTenantId",
            "summary": "Generated\u0020from\u0020protobuf\u0020field\u0020\u003Ccode\u003Estring\u0020tenant_id\u0020\u003D\u00201\u003B\u003C\/code\u003E",
            "url": "classes/Proto-IronCoreLabs-SaaSShieldHeader.html#method_getTenantId"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\SaaSShieldHeader\u003A\u003AsetTenantId\u0028\u0029",
            "name": "setTenantId",
            "summary": "Generated\u0020from\u0020protobuf\u0020field\u0020\u003Ccode\u003Estring\u0020tenant_id\u0020\u003D\u00201\u003B\u003C\/code\u003E",
            "url": "classes/Proto-IronCoreLabs-SaaSShieldHeader.html#method_setTenantId"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\SaaSShieldHeader\u003A\u003A\u0024tenant_id",
            "name": "tenant_id",
            "summary": "Generated\u0020from\u0020protobuf\u0020field\u0020\u003Ccode\u003Estring\u0020tenant_id\u0020\u003D\u00201\u003B\u003C\/code\u003E",
            "url": "classes/Proto-IronCoreLabs-SaaSShieldHeader.html#property_tenant_id"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\V3DocumentHeader",
            "name": "V3DocumentHeader",
            "summary": "Generated\u0020from\u0020protobuf\u0020message\u0020\u003Ccode\u003Eproto.ironcorelabs.cmk.V3DocumentHeader\u003C\/code\u003E",
            "url": "classes/Proto-IronCoreLabs-V3DocumentHeader.html"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\V3DocumentHeader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Proto-IronCoreLabs-V3DocumentHeader.html#method___construct"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\V3DocumentHeader\u003A\u003AgetSig\u0028\u0029",
            "name": "getSig",
            "summary": "Generated\u0020from\u0020protobuf\u0020field\u0020\u003Ccode\u003Ebytes\u0020sig\u0020\u003D\u00201\u003B\u003C\/code\u003E",
            "url": "classes/Proto-IronCoreLabs-V3DocumentHeader.html#method_getSig"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\V3DocumentHeader\u003A\u003AsetSig\u0028\u0029",
            "name": "setSig",
            "summary": "Generated\u0020from\u0020protobuf\u0020field\u0020\u003Ccode\u003Ebytes\u0020sig\u0020\u003D\u00201\u003B\u003C\/code\u003E",
            "url": "classes/Proto-IronCoreLabs-V3DocumentHeader.html#method_setSig"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\V3DocumentHeader\u003A\u003AgetDataControl\u0028\u0029",
            "name": "getDataControl",
            "summary": "Generated\u0020from\u0020protobuf\u0020field\u0020\u003Ccode\u003E.proto.ironcorelabs.cmk.DataControlPlatformHeader\u0020data_control\u0020\u003D\u00202\u003B\u003C\/code\u003E",
            "url": "classes/Proto-IronCoreLabs-V3DocumentHeader.html#method_getDataControl"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\V3DocumentHeader\u003A\u003AhasDataControl\u0028\u0029",
            "name": "hasDataControl",
            "summary": "",
            "url": "classes/Proto-IronCoreLabs-V3DocumentHeader.html#method_hasDataControl"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\V3DocumentHeader\u003A\u003AsetDataControl\u0028\u0029",
            "name": "setDataControl",
            "summary": "Generated\u0020from\u0020protobuf\u0020field\u0020\u003Ccode\u003E.proto.ironcorelabs.cmk.DataControlPlatformHeader\u0020data_control\u0020\u003D\u00202\u003B\u003C\/code\u003E",
            "url": "classes/Proto-IronCoreLabs-V3DocumentHeader.html#method_setDataControl"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\V3DocumentHeader\u003A\u003AgetSaasShield\u0028\u0029",
            "name": "getSaasShield",
            "summary": "Generated\u0020from\u0020protobuf\u0020field\u0020\u003Ccode\u003E.proto.ironcorelabs.cmk.SaaSShieldHeader\u0020saas_shield\u0020\u003D\u00203\u003B\u003C\/code\u003E",
            "url": "classes/Proto-IronCoreLabs-V3DocumentHeader.html#method_getSaasShield"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\V3DocumentHeader\u003A\u003AhasSaasShield\u0028\u0029",
            "name": "hasSaasShield",
            "summary": "",
            "url": "classes/Proto-IronCoreLabs-V3DocumentHeader.html#method_hasSaasShield"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\V3DocumentHeader\u003A\u003AsetSaasShield\u0028\u0029",
            "name": "setSaasShield",
            "summary": "Generated\u0020from\u0020protobuf\u0020field\u0020\u003Ccode\u003E.proto.ironcorelabs.cmk.SaaSShieldHeader\u0020saas_shield\u0020\u003D\u00203\u003B\u003C\/code\u003E",
            "url": "classes/Proto-IronCoreLabs-V3DocumentHeader.html#method_setSaasShield"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\V3DocumentHeader\u003A\u003AgetHeader\u0028\u0029",
            "name": "getHeader",
            "summary": "",
            "url": "classes/Proto-IronCoreLabs-V3DocumentHeader.html#method_getHeader"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\V3DocumentHeader\u003A\u003A\u0024sig",
            "name": "sig",
            "summary": "Generated\u0020from\u0020protobuf\u0020field\u0020\u003Ccode\u003Ebytes\u0020sig\u0020\u003D\u00201\u003B\u003C\/code\u003E",
            "url": "classes/Proto-IronCoreLabs-V3DocumentHeader.html#property_sig"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs\\V3DocumentHeader\u003A\u003A\u0024header",
            "name": "header",
            "summary": "",
            "url": "classes/Proto-IronCoreLabs-V3DocumentHeader.html#property_header"
        },                {
            "fqsen": "\\IronCore\\RequestMetadata",
            "name": "RequestMetadata",
            "summary": "Holds\u0020metadata\u0020fields\u0020as\u0020part\u0020of\u0020an\u0020encrypted\u0020document.\u0020Each\u0020document\u0020has\u0020metadata\u0020associated\u0020with\u0020it\nthat\u0020will\u0020be\u0020sent\u0020to\u0020the\u0020Tenant\u0020Security\u0020Proxy\u0020for\u0020logging\u0020and\u0020other\u0020purposes.\u0020Some\u0020examples\u0020include\nthe\u0020tenant\u0020ID\u0020associated\u0020with\u0020the\u0020request,\u0020the\u0020service\u0020that\u0020is\u0020accessing\u0020the\u0020data,\u0020and\u0020a\u0020unique\u0020ID\nfor\u0020the\u0020request.",
            "url": "classes/IronCore-RequestMetadata.html"
        },                {
            "fqsen": "\\IronCore\\RequestMetadata\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-RequestMetadata.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\RequestMetadata\u003A\u003AgetTenantId\u0028\u0029",
            "name": "getTenantId",
            "summary": "Gets\u0020the\u0020ID\u0020of\u0020the\u0020tenant\u0020making\u0020the\u0020request.",
            "url": "classes/IronCore-RequestMetadata.html#method_getTenantId"
        },                {
            "fqsen": "\\IronCore\\RequestMetadata\u003A\u003AgetPostData\u0028\u0029",
            "name": "getPostData",
            "summary": "Gets\u0020an\u0020associative\u0020array\u0020of\u0020data\u0020that\u0020can\u0020be\u0020serialized\nand\u0020sent\u0020to\u0020the\u0020Tenant\u0020Security\u0020Proxy.",
            "url": "classes/IronCore-RequestMetadata.html#method_getPostData"
        },                {
            "fqsen": "\\IronCore\\RequestMetadata\u003A\u003A\u0024tenantId",
            "name": "tenantId",
            "summary": "",
            "url": "classes/IronCore-RequestMetadata.html#property_tenantId"
        },                {
            "fqsen": "\\IronCore\\RequestMetadata\u003A\u003A\u0024iclFields",
            "name": "iclFields",
            "summary": "",
            "url": "classes/IronCore-RequestMetadata.html#property_iclFields"
        },                {
            "fqsen": "\\IronCore\\RequestMetadata\u003A\u003A\u0024customFields",
            "name": "customFields",
            "summary": "",
            "url": "classes/IronCore-RequestMetadata.html#property_customFields"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchUnwrapKeyRequest",
            "name": "BatchUnwrapKeyRequest",
            "summary": "Request\u0020to\u0020the\u0020Tenant\u0020Security\u0020Proxy\u0027s\u0020batch\u0020unwrap\u0020keys\u0020endpoint",
            "url": "classes/IronCore-Rest-BatchUnwrapKeyRequest.html"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchUnwrapKeyRequest\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-Rest-BatchUnwrapKeyRequest.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchUnwrapKeyRequest\u003A\u003AgetPostData\u0028\u0029",
            "name": "getPostData",
            "summary": "Method\u0020to\u0020get\u0020the\u0020request\u0020data\u0020as\u0020an\u0020associative\u0020array.",
            "url": "classes/IronCore-Rest-BatchUnwrapKeyRequest.html#method_getPostData"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchUnwrapKeyRequest\u003A\u003A\u0024metadata",
            "name": "metadata",
            "summary": "",
            "url": "classes/IronCore-Rest-BatchUnwrapKeyRequest.html#property_metadata"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchUnwrapKeyRequest\u003A\u003A\u0024edeks",
            "name": "edeks",
            "summary": "",
            "url": "classes/IronCore-Rest-BatchUnwrapKeyRequest.html#property_edeks"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchUnwrapKeyResponse",
            "name": "BatchUnwrapKeyResponse",
            "summary": "Response\u0020from\u0020the\u0020Tenant\u0020Security\u0020Proxy\u0027s\u0020batch\u0020unwrap\u0020key\u0020endpoint",
            "url": "classes/IronCore-Rest-BatchUnwrapKeyResponse.html"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchUnwrapKeyResponse\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-Rest-BatchUnwrapKeyResponse.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchUnwrapKeyResponse\u003A\u003AfromResponse\u0028\u0029",
            "name": "fromResponse",
            "summary": "",
            "url": "classes/IronCore-Rest-BatchUnwrapKeyResponse.html#method_fromResponse"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchUnwrapKeyResponse\u003A\u003AgetKeys\u0028\u0029",
            "name": "getKeys",
            "summary": "",
            "url": "classes/IronCore-Rest-BatchUnwrapKeyResponse.html#method_getKeys"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchUnwrapKeyResponse\u003A\u003AgetFailures\u0028\u0029",
            "name": "getFailures",
            "summary": "",
            "url": "classes/IronCore-Rest-BatchUnwrapKeyResponse.html#method_getFailures"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchUnwrapKeyResponse\u003A\u003A\u0024keys",
            "name": "keys",
            "summary": "",
            "url": "classes/IronCore-Rest-BatchUnwrapKeyResponse.html#property_keys"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchUnwrapKeyResponse\u003A\u003A\u0024failures",
            "name": "failures",
            "summary": "",
            "url": "classes/IronCore-Rest-BatchUnwrapKeyResponse.html#property_failures"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchWrapKeyRequest",
            "name": "BatchWrapKeyRequest",
            "summary": "Request\u0020to\u0020the\u0020Tenant\u0020Security\u0020Proxy\u0027s\u0020batch\u0020wrap\u0020keys\u0020endpoint",
            "url": "classes/IronCore-Rest-BatchWrapKeyRequest.html"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchWrapKeyRequest\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-Rest-BatchWrapKeyRequest.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchWrapKeyRequest\u003A\u003AgetPostData\u0028\u0029",
            "name": "getPostData",
            "summary": "Method\u0020to\u0020get\u0020the\u0020request\u0020data\u0020as\u0020an\u0020associative\u0020array.",
            "url": "classes/IronCore-Rest-BatchWrapKeyRequest.html#method_getPostData"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchWrapKeyRequest\u003A\u003A\u0024metadata",
            "name": "metadata",
            "summary": "",
            "url": "classes/IronCore-Rest-BatchWrapKeyRequest.html#property_metadata"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchWrapKeyRequest\u003A\u003A\u0024documentIds",
            "name": "documentIds",
            "summary": "",
            "url": "classes/IronCore-Rest-BatchWrapKeyRequest.html#property_documentIds"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchWrapKeyResponse",
            "name": "BatchWrapKeyResponse",
            "summary": "Response\u0020from\u0020the\u0020Tenant\u0020Security\u0020Proxy\u0027s\u0020batch\u0020wrap\u0020key\u0020endpoint",
            "url": "classes/IronCore-Rest-BatchWrapKeyResponse.html"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchWrapKeyResponse\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-Rest-BatchWrapKeyResponse.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchWrapKeyResponse\u003A\u003AfromResponse\u0028\u0029",
            "name": "fromResponse",
            "summary": "",
            "url": "classes/IronCore-Rest-BatchWrapKeyResponse.html#method_fromResponse"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchWrapKeyResponse\u003A\u003AgetKeys\u0028\u0029",
            "name": "getKeys",
            "summary": "",
            "url": "classes/IronCore-Rest-BatchWrapKeyResponse.html#method_getKeys"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchWrapKeyResponse\u003A\u003AgetFailures\u0028\u0029",
            "name": "getFailures",
            "summary": "",
            "url": "classes/IronCore-Rest-BatchWrapKeyResponse.html#method_getFailures"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchWrapKeyResponse\u003A\u003A\u0024keys",
            "name": "keys",
            "summary": "",
            "url": "classes/IronCore-Rest-BatchWrapKeyResponse.html#property_keys"
        },                {
            "fqsen": "\\IronCore\\Rest\\BatchWrapKeyResponse\u003A\u003A\u0024failures",
            "name": "failures",
            "summary": "",
            "url": "classes/IronCore-Rest-BatchWrapKeyResponse.html#property_failures"
        },                {
            "fqsen": "\\IronCore\\Rest\\IronCoreRequest",
            "name": "IronCoreRequest",
            "summary": "Abstract\u0020class\u0020representing\u0020a\u0020Tenant\u0020Security\u0020Proxy\u0020request\u0020object.",
            "url": "classes/IronCore-Rest-IronCoreRequest.html"
        },                {
            "fqsen": "\\IronCore\\Rest\\IronCoreRequest\u003A\u003AgetJsonData\u0028\u0029",
            "name": "getJsonData",
            "summary": "Gets\u0020the\u0020JSON\u002Dencoded\u0020form\u0020of\u0020the\u0020request\u0020payload.",
            "url": "classes/IronCore-Rest-IronCoreRequest.html#method_getJsonData"
        },                {
            "fqsen": "\\IronCore\\Rest\\IronCoreRequest\u003A\u003AgetPostData\u0028\u0029",
            "name": "getPostData",
            "summary": "Method\u0020to\u0020get\u0020the\u0020request\u0020data\u0020as\u0020an\u0020associative\u0020array.",
            "url": "classes/IronCore-Rest-IronCoreRequest.html#method_getPostData"
        },                {
            "fqsen": "\\IronCore\\Rest\\LogSecurityEventRequest",
            "name": "LogSecurityEventRequest",
            "summary": "Request\u0020to\u0020the\u0020Tenant\u0020Security\u0020Proxy\u0027s\u0020security\u0020event\u0020logging\u0020endpoint",
            "url": "classes/IronCore-Rest-LogSecurityEventRequest.html"
        },                {
            "fqsen": "\\IronCore\\Rest\\LogSecurityEventRequest\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-Rest-LogSecurityEventRequest.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\Rest\\LogSecurityEventRequest\u003A\u003AgetPostData\u0028\u0029",
            "name": "getPostData",
            "summary": "Method\u0020to\u0020get\u0020the\u0020request\u0020data\u0020as\u0020an\u0020associative\u0020array.",
            "url": "classes/IronCore-Rest-LogSecurityEventRequest.html#method_getPostData"
        },                {
            "fqsen": "\\IronCore\\Rest\\LogSecurityEventRequest\u003A\u003A\u0024metadata",
            "name": "metadata",
            "summary": "",
            "url": "classes/IronCore-Rest-LogSecurityEventRequest.html#property_metadata"
        },                {
            "fqsen": "\\IronCore\\Rest\\LogSecurityEventRequest\u003A\u003A\u0024event",
            "name": "event",
            "summary": "",
            "url": "classes/IronCore-Rest-LogSecurityEventRequest.html#property_event"
        },                {
            "fqsen": "\\IronCore\\Rest\\RekeyRequest",
            "name": "RekeyRequest",
            "summary": "Request\u0020to\u0020the\u0020Tenant\u0020Security\u0020Proxy\u0027s\u0020re\u002Dkey\u0020endpoint",
            "url": "classes/IronCore-Rest-RekeyRequest.html"
        },                {
            "fqsen": "\\IronCore\\Rest\\RekeyRequest\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-Rest-RekeyRequest.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\Rest\\RekeyRequest\u003A\u003AgetPostData\u0028\u0029",
            "name": "getPostData",
            "summary": "Method\u0020to\u0020get\u0020the\u0020request\u0020data\u0020as\u0020an\u0020associative\u0020array.",
            "url": "classes/IronCore-Rest-RekeyRequest.html#method_getPostData"
        },                {
            "fqsen": "\\IronCore\\Rest\\RekeyRequest\u003A\u003A\u0024metadata",
            "name": "metadata",
            "summary": "",
            "url": "classes/IronCore-Rest-RekeyRequest.html#property_metadata"
        },                {
            "fqsen": "\\IronCore\\Rest\\RekeyRequest\u003A\u003A\u0024edek",
            "name": "edek",
            "summary": "",
            "url": "classes/IronCore-Rest-RekeyRequest.html#property_edek"
        },                {
            "fqsen": "\\IronCore\\Rest\\RekeyRequest\u003A\u003A\u0024newTenantId",
            "name": "newTenantId",
            "summary": "",
            "url": "classes/IronCore-Rest-RekeyRequest.html#property_newTenantId"
        },                {
            "fqsen": "\\IronCore\\Rest\\RekeyResponse",
            "name": "RekeyResponse",
            "summary": "Response\u0020from\u0020the\u0020Tenant\u0020Security\u0020Proxy\u0027s\u0020re\u002Dkey\u0020endpoint",
            "url": "classes/IronCore-Rest-RekeyResponse.html"
        },                {
            "fqsen": "\\IronCore\\Rest\\RekeyResponse\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-Rest-RekeyResponse.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\Rest\\RekeyResponse\u003A\u003AfromResponse\u0028\u0029",
            "name": "fromResponse",
            "summary": "Converts\u0020from\u0020a\u0020TSP\u0020response\u0020to\u0020a\u0020RekeyResponse.",
            "url": "classes/IronCore-Rest-RekeyResponse.html#method_fromResponse"
        },                {
            "fqsen": "\\IronCore\\Rest\\RekeyResponse\u003A\u003AgetDek\u0028\u0029",
            "name": "getDek",
            "summary": "Gets\u0020the\u0020document\u0020key\u0020sent\u0020back\u0020from\u0020the\u0020TSP.",
            "url": "classes/IronCore-Rest-RekeyResponse.html#method_getDek"
        },                {
            "fqsen": "\\IronCore\\Rest\\RekeyResponse\u003A\u003AgetEdek\u0028\u0029",
            "name": "getEdek",
            "summary": "Gets\u0020the\u0020encrypted\u0020document\u0020key\u0020sent\u0020back\u0020from\u0020the\u0020TSP.",
            "url": "classes/IronCore-Rest-RekeyResponse.html#method_getEdek"
        },                {
            "fqsen": "\\IronCore\\Rest\\RekeyResponse\u003A\u003A\u0024dek",
            "name": "dek",
            "summary": "",
            "url": "classes/IronCore-Rest-RekeyResponse.html#property_dek"
        },                {
            "fqsen": "\\IronCore\\Rest\\RekeyResponse\u003A\u003A\u0024edek",
            "name": "edek",
            "summary": "",
            "url": "classes/IronCore-Rest-RekeyResponse.html#property_edek"
        },                {
            "fqsen": "\\IronCore\\Rest\\UnwrapKeyRequest",
            "name": "UnwrapKeyRequest",
            "summary": "Request\u0020to\u0020the\u0020Tenant\u0020Security\u0020Proxy\u0027s\u0020unwrap\u0020key\u0020endpoint",
            "url": "classes/IronCore-Rest-UnwrapKeyRequest.html"
        },                {
            "fqsen": "\\IronCore\\Rest\\UnwrapKeyRequest\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-Rest-UnwrapKeyRequest.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\Rest\\UnwrapKeyRequest\u003A\u003AgetPostData\u0028\u0029",
            "name": "getPostData",
            "summary": "Method\u0020to\u0020get\u0020the\u0020request\u0020data\u0020as\u0020an\u0020associative\u0020array.",
            "url": "classes/IronCore-Rest-UnwrapKeyRequest.html#method_getPostData"
        },                {
            "fqsen": "\\IronCore\\Rest\\UnwrapKeyRequest\u003A\u003A\u0024metadata",
            "name": "metadata",
            "summary": "",
            "url": "classes/IronCore-Rest-UnwrapKeyRequest.html#property_metadata"
        },                {
            "fqsen": "\\IronCore\\Rest\\UnwrapKeyRequest\u003A\u003A\u0024edek",
            "name": "edek",
            "summary": "",
            "url": "classes/IronCore-Rest-UnwrapKeyRequest.html#property_edek"
        },                {
            "fqsen": "\\IronCore\\Rest\\UnwrapKeyResponse",
            "name": "UnwrapKeyResponse",
            "summary": "Response\u0020from\u0020the\u0020Tenant\u0020Security\u0020Proxy\u0027s\u0020unwrap\u0020key\u0020endpoint",
            "url": "classes/IronCore-Rest-UnwrapKeyResponse.html"
        },                {
            "fqsen": "\\IronCore\\Rest\\UnwrapKeyResponse\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-Rest-UnwrapKeyResponse.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\Rest\\UnwrapKeyResponse\u003A\u003AfromResponse\u0028\u0029",
            "name": "fromResponse",
            "summary": "Converts\u0020from\u0020a\u0020TSP\u0020response\u0020to\u0020an\u0020UnwrapKeyResponse.",
            "url": "classes/IronCore-Rest-UnwrapKeyResponse.html#method_fromResponse"
        },                {
            "fqsen": "\\IronCore\\Rest\\UnwrapKeyResponse\u003A\u003AgetDek\u0028\u0029",
            "name": "getDek",
            "summary": "Gets\u0020the\u0020document\u0020key\u0020sent\u0020back\u0020from\u0020the\u0020TSP.",
            "url": "classes/IronCore-Rest-UnwrapKeyResponse.html#method_getDek"
        },                {
            "fqsen": "\\IronCore\\Rest\\UnwrapKeyResponse\u003A\u003A\u0024dek",
            "name": "dek",
            "summary": "",
            "url": "classes/IronCore-Rest-UnwrapKeyResponse.html#property_dek"
        },                {
            "fqsen": "\\IronCore\\Rest\\WrapKeyRequest",
            "name": "WrapKeyRequest",
            "summary": "Request\u0020to\u0020the\u0020Tenant\u0020Security\u0020Proxy\u0027s\u0020wrap\u0020key\u0020endpoint",
            "url": "classes/IronCore-Rest-WrapKeyRequest.html"
        },                {
            "fqsen": "\\IronCore\\Rest\\WrapKeyRequest\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-Rest-WrapKeyRequest.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\Rest\\WrapKeyRequest\u003A\u003AgetPostData\u0028\u0029",
            "name": "getPostData",
            "summary": "Method\u0020to\u0020get\u0020the\u0020request\u0020data\u0020as\u0020an\u0020associative\u0020array.",
            "url": "classes/IronCore-Rest-WrapKeyRequest.html#method_getPostData"
        },                {
            "fqsen": "\\IronCore\\Rest\\WrapKeyRequest\u003A\u003A\u0024metadata",
            "name": "metadata",
            "summary": "",
            "url": "classes/IronCore-Rest-WrapKeyRequest.html#property_metadata"
        },                {
            "fqsen": "\\IronCore\\Rest\\WrapKeyResponse",
            "name": "WrapKeyResponse",
            "summary": "Response\u0020from\u0020the\u0020Tenant\u0020Security\u0020Proxy\u0027s\u0020wrap\u0020key\u0020endpoint",
            "url": "classes/IronCore-Rest-WrapKeyResponse.html"
        },                {
            "fqsen": "\\IronCore\\Rest\\WrapKeyResponse\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-Rest-WrapKeyResponse.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\Rest\\WrapKeyResponse\u003A\u003AfromResponse\u0028\u0029",
            "name": "fromResponse",
            "summary": "Converts\u0020from\u0020a\u0020TSP\u0020response\u0020to\u0020a\u0020WrapKeyResponse.",
            "url": "classes/IronCore-Rest-WrapKeyResponse.html#method_fromResponse"
        },                {
            "fqsen": "\\IronCore\\Rest\\WrapKeyResponse\u003A\u003AgetDek\u0028\u0029",
            "name": "getDek",
            "summary": "Gets\u0020the\u0020document\u0020key\u0020sent\u0020back\u0020from\u0020the\u0020TSP.",
            "url": "classes/IronCore-Rest-WrapKeyResponse.html#method_getDek"
        },                {
            "fqsen": "\\IronCore\\Rest\\WrapKeyResponse\u003A\u003AgetEdek\u0028\u0029",
            "name": "getEdek",
            "summary": "Gets\u0020the\u0020encrypted\u0020document\u0020key\u0020sent\u0020back\u0020from\u0020the\u0020TSP.",
            "url": "classes/IronCore-Rest-WrapKeyResponse.html#method_getEdek"
        },                {
            "fqsen": "\\IronCore\\Rest\\WrapKeyResponse\u003A\u003A\u0024dek",
            "name": "dek",
            "summary": "",
            "url": "classes/IronCore-Rest-WrapKeyResponse.html#property_dek"
        },                {
            "fqsen": "\\IronCore\\Rest\\WrapKeyResponse\u003A\u003A\u0024edek",
            "name": "edek",
            "summary": "",
            "url": "classes/IronCore-Rest-WrapKeyResponse.html#property_edek"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\AdminEvent",
            "name": "AdminEvent",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-AdminEvent.html"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\AdminEvent\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-AdminEvent.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\AdminEvent\u003A\u003AgetFlatEvent\u0028\u0029",
            "name": "getFlatEvent",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-AdminEvent.html#method_getFlatEvent"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\AdminEvent\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-AdminEvent.html#method_add"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\AdminEvent\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-AdminEvent.html#method_remove"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\AdminEvent\u003A\u003AchangePermissions\u0028\u0029",
            "name": "changePermissions",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-AdminEvent.html#method_changePermissions"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\AdminEvent\u003A\u003AchangeSetting\u0028\u0029",
            "name": "changeSetting",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-AdminEvent.html#method_changeSetting"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\AdminEvent\u003A\u003A\u0024flatEvent",
            "name": "flatEvent",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-AdminEvent.html#property_flatEvent"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\CustomEvent",
            "name": "CustomEvent",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-CustomEvent.html"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\CustomEvent\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-CustomEvent.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\CustomEvent\u003A\u003AgetFlatEvent\u0028\u0029",
            "name": "getFlatEvent",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-CustomEvent.html#method_getFlatEvent"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\CustomEvent\u003A\u003AcustomEvent\u0028\u0029",
            "name": "customEvent",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-CustomEvent.html#method_customEvent"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\CustomEvent\u003A\u003A\u0024flatEvent",
            "name": "flatEvent",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-CustomEvent.html#property_flatEvent"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\DataEvent",
            "name": "DataEvent",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-DataEvent.html"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\DataEvent\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-DataEvent.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\DataEvent\u003A\u003AgetFlatEvent\u0028\u0029",
            "name": "getFlatEvent",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-DataEvent.html#method_getFlatEvent"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\DataEvent\u003A\u003Aimport\u0028\u0029",
            "name": "import",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-DataEvent.html#method_import"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\DataEvent\u003A\u003Aexport\u0028\u0029",
            "name": "export",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-DataEvent.html#method_export"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\DataEvent\u003A\u003Aencrypt\u0028\u0029",
            "name": "encrypt",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-DataEvent.html#method_encrypt"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\DataEvent\u003A\u003Adecrypt\u0028\u0029",
            "name": "decrypt",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-DataEvent.html#method_decrypt"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\DataEvent\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-DataEvent.html#method_create"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\DataEvent\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-DataEvent.html#method_delete"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\DataEvent\u003A\u003AdenyAccess\u0028\u0029",
            "name": "denyAccess",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-DataEvent.html#method_denyAccess"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\DataEvent\u003A\u003AchangePermissions\u0028\u0029",
            "name": "changePermissions",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-DataEvent.html#method_changePermissions"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\DataEvent\u003A\u003A\u0024flatEvent",
            "name": "flatEvent",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-DataEvent.html#property_flatEvent"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\PeriodicEvent",
            "name": "PeriodicEvent",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-PeriodicEvent.html"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\PeriodicEvent\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-PeriodicEvent.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\PeriodicEvent\u003A\u003AgetFlatEvent\u0028\u0029",
            "name": "getFlatEvent",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-PeriodicEvent.html#method_getFlatEvent"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\PeriodicEvent\u003A\u003AenforceRetentionPolicy\u0028\u0029",
            "name": "enforceRetentionPolicy",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-PeriodicEvent.html#method_enforceRetentionPolicy"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\PeriodicEvent\u003A\u003AcreateBackup\u0028\u0029",
            "name": "createBackup",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-PeriodicEvent.html#method_createBackup"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\PeriodicEvent\u003A\u003A\u0024flatEvent",
            "name": "flatEvent",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-PeriodicEvent.html#property_flatEvent"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\SecurityEvent",
            "name": "SecurityEvent",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-SecurityEvent.html"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\SecurityEvent\u003A\u003AgetFlatEvent\u0028\u0029",
            "name": "getFlatEvent",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-SecurityEvent.html#method_getFlatEvent"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent",
            "name": "UserEvent",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent\u003A\u003AgetFlatEvent\u0028\u0029",
            "name": "getFlatEvent",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html#method_getFlatEvent"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html#method_add"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent\u003A\u003Asuspend\u0028\u0029",
            "name": "suspend",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html#method_suspend"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html#method_remove"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html#method_login"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent\u003A\u003AtimeoutSession\u0028\u0029",
            "name": "timeoutSession",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html#method_timeoutSession"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent\u003A\u003Alockout\u0028\u0029",
            "name": "lockout",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html#method_lockout"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html#method_logout"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent\u003A\u003AchangePermissions\u0028\u0029",
            "name": "changePermissions",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html#method_changePermissions"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent\u003A\u003AexpirePassword\u0028\u0029",
            "name": "expirePassword",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html#method_expirePassword"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent\u003A\u003AresetPassword\u0028\u0029",
            "name": "resetPassword",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html#method_resetPassword"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent\u003A\u003AchangePassword\u0028\u0029",
            "name": "changePassword",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html#method_changePassword"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent\u003A\u003ArejectLogin\u0028\u0029",
            "name": "rejectLogin",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html#method_rejectLogin"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent\u003A\u003AenableTwoFactor\u0028\u0029",
            "name": "enableTwoFactor",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html#method_enableTwoFactor"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent\u003A\u003AdisableTwoFactor\u0028\u0029",
            "name": "disableTwoFactor",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html#method_disableTwoFactor"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent\u003A\u003AchangeEmail\u0028\u0029",
            "name": "changeEmail",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html#method_changeEmail"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent\u003A\u003ArequestEmailVerification\u0028\u0029",
            "name": "requestEmailVerification",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html#method_requestEmailVerification"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent\u003A\u003AverifyEmail\u0028\u0029",
            "name": "verifyEmail",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html#method_verifyEmail"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents\\UserEvent\u003A\u003A\u0024flatEvent",
            "name": "flatEvent",
            "summary": "",
            "url": "classes/IronCore-SecurityEvents-UserEvent.html#property_flatEvent"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityClient",
            "name": "TenantSecurityClient",
            "summary": "Client\u0020used\u0020to\u0020encrypt\u0020and\u0020decrypt\u0020documents.\u0020This\u0020is\u0020the\u0020primary\u0020class\u0020that\u0020consumers\u0020of\u0020the\nlibrary\u0020will\u0020need\u0020to\u0020utilize,\u0020and\u0020a\u0020single\u0020instance\u0020of\u0020the\u0020class\u0020can\u0020be\u0020re\u002Dused\u0020for\u0020requests\nacross\u0020different\u0020tenants.",
            "url": "classes/IronCore-TenantSecurityClient.html"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityClient\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-TenantSecurityClient.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityClient\u003A\u003Aencrypt\u0028\u0029",
            "name": "encrypt",
            "summary": "Encrypts\u0020the\u0020provided\u0020document.\u0020Documents\u0020are\u0020provided\u0020as\u0020a\u0020map\u0020of\u0020fields\u0020from\u0020the\u0020document\nid\/name\u0020\u0028string\u0029\u0020to\u0020bytes\u0020\u0028string\u0029.\u0020Uses\u0020the\u0020Tenant\u0020Security\u0020Proxy\u0020to\u0020generate\u0020a\u0020new\u0020document\nencryption\u0020key\u0020\u0028DEK\u0029,\u0020encrypt\u0020that\u0020key\u0020\u0028EDEK\u0029,\u0020then\u0020use\u0020the\u0020DEK\u0020to\u0020encrypt\u0020all\u0020of\u0020the\nprovided\u0020document\u0020fields.\u0020Returns\u0020an\u0020EncryptedDocument\u0020which\u0020contains\u0020a\u0020Map\u0020from\u0020each\u0020field\u0027s\nid\/name\u0020to\u0020encrypted\u0020bytes\u0020as\u0020well\u0020as\u0020the\u0020EDEK\u0020and\u0020discards\u0020the\u0020DEK.",
            "url": "classes/IronCore-TenantSecurityClient.html#method_encrypt"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityClient\u003A\u003AbatchEncrypt\u0028\u0029",
            "name": "batchEncrypt",
            "summary": "Encrypts\u0020an\u0020array\u0020of\u0020documents\u0020from\u0020the\u0020ID\u0020of\u0020the\u0020document\u0020to\u0020the\u0020list\u0020of\u0020fields\u0020to\u0020encrypt.",
            "url": "classes/IronCore-TenantSecurityClient.html#method_batchEncrypt"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityClient\u003A\u003Adecrypt\u0028\u0029",
            "name": "decrypt",
            "summary": "Decrypts\u0020the\u0020provided\u0020EncryptedDocument.\u0020Decrypts\u0020the\u0020document\u0027s\u0020encrypted\u0020document\u0020key\u0020\u0028EDEK\u0029\nusing\u0020the\u0020Tenant\u0020Security\u0020Proxy\u0020and\u0020uses\u0020it\u0020to\u0020decrypt\u0020and\u0020return\u0020the\u0020document\u0020bytes.\u0020The\u0020DEK\nis\u0020then\u0020discarded.",
            "url": "classes/IronCore-TenantSecurityClient.html#method_decrypt"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityClient\u003A\u003AbatchDecrypt\u0028\u0029",
            "name": "batchDecrypt",
            "summary": "Decrypts\u0020a\u0020map\u0020of\u0020documents\u0020from\u0020the\u0020ID\u0020of\u0020the\u0020document\u0020to\u0020its\u0020encrypted\u0020content.\u0020Makes\u0020a\u0020call\nout\u0020to\u0020the\u0020Tenant\u0020Security\u0020Proxy\u0020to\u0020decrypt\u0020all\u0020of\u0020the\u0020EDEKs\u0020in\u0020each\u0020document.\u0020This\u0020function\nsupports\u0020partial\u0020failure\u0020so\u0020it\u0020returns\u0020two\u0020Maps,\u0020one\u0020of\u0020document\u0020ID\u0020to\u0020successfully\u0020decrypted\ndocument\u0020and\u0020one\u0020of\u0020document\u0020ID\u0020to\u0020a\u0020TenantSecurityException.",
            "url": "classes/IronCore-TenantSecurityClient.html#method_batchDecrypt"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityClient\u003A\u003ArekeyEdek\u0028\u0029",
            "name": "rekeyEdek",
            "summary": "Re\u002Dkey\u0020a\u0020document\u0027s\u0020encrypted\u0020document\u0020key\u0020\u0028EDEK\u0029\u0020to\u0020a\u0020new\u0020tenant.\u0020Decrypts\u0020the\u0020EDEK\u0020then\u0020re\u002Dencrypts\u0020it\u0020to\u0020the\nnew\u0020tenant.\u0020The\u0020DEK\u0020is\u0020then\u0020discarded.\u0020The\u0020old\u0020tenant\u0020and\u0020new\u0020tenant\u0020can\u0020be\u0020the\u0020same\u0020in\u0020order\u0020to\u0020re\u002Dkey\u0020the\ndocument\u0020to\u0020the\u0020tenant\u0027s\u0020latest\u0020primary\u0020config.",
            "url": "classes/IronCore-TenantSecurityClient.html#method_rekeyEdek"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityClient\u003A\u003AlogSecurityEvent\u0028\u0029",
            "name": "logSecurityEvent",
            "summary": "Send\u0020the\u0020provided\u0020security\u0020event\u0020to\u0020the\u0020TSP\u0020to\u0020be\u0020logged\u0020and\u0020analyzed.\u0020Note\u0020that\u0020logging\u0020a\u0020security\u0020event\u0020is\u0020an\nasynchronous\u0020operation\u0020at\u0020the\u0020TSP,\u0020so\u0020successful\u0020receipt\u0020of\u0020a\u0020security\u0020event\u0020does\u0020not\u0020mean\nthat\u0020the\u0020event\u0020is\u0020deliverable\u0020or\u0020has\u0020been\u0020delivered\u0020to\u0020the\u0020tenant\u0027s\u0020logging\u0020system.\u0020It\u0020simply\nmeans\u0020that\u0020the\u0020event\u0020has\u0020been\u0020received\u0020and\u0020will\u0020be\u0020processed.",
            "url": "classes/IronCore-TenantSecurityClient.html#method_logSecurityEvent"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityClient\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/IronCore-TenantSecurityClient.html#property_request"
        },                {
            "fqsen": "\\IronCore\\TSP_API_PREFIX",
            "name": "TSP_API_PREFIX",
            "summary": "",
            "url": "namespaces/ironcore.html#constant_TSP_API_PREFIX"
        },                {
            "fqsen": "\\IronCore\\WRAP_ENDPOINT",
            "name": "WRAP_ENDPOINT",
            "summary": "",
            "url": "namespaces/ironcore.html#constant_WRAP_ENDPOINT"
        },                {
            "fqsen": "\\IronCore\\BATCH_WRAP_ENDPOINT",
            "name": "BATCH_WRAP_ENDPOINT",
            "summary": "",
            "url": "namespaces/ironcore.html#constant_BATCH_WRAP_ENDPOINT"
        },                {
            "fqsen": "\\IronCore\\UNWRAP_ENDPOINT",
            "name": "UNWRAP_ENDPOINT",
            "summary": "",
            "url": "namespaces/ironcore.html#constant_UNWRAP_ENDPOINT"
        },                {
            "fqsen": "\\IronCore\\BATCH_UNWRAP_ENDPOINT",
            "name": "BATCH_UNWRAP_ENDPOINT",
            "summary": "",
            "url": "namespaces/ironcore.html#constant_BATCH_UNWRAP_ENDPOINT"
        },                {
            "fqsen": "\\IronCore\\REKEY_ENDPOINT",
            "name": "REKEY_ENDPOINT",
            "summary": "",
            "url": "namespaces/ironcore.html#constant_REKEY_ENDPOINT"
        },                {
            "fqsen": "\\IronCore\\TENANT_KEY_DERIVE_ENDPOINT",
            "name": "TENANT_KEY_DERIVE_ENDPOINT",
            "summary": "",
            "url": "namespaces/ironcore.html#constant_TENANT_KEY_DERIVE_ENDPOINT"
        },                {
            "fqsen": "\\IronCore\\SECURITY_EVENT_ENDPOINT",
            "name": "SECURITY_EVENT_ENDPOINT",
            "summary": "",
            "url": "namespaces/ironcore.html#constant_SECURITY_EVENT_ENDPOINT"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityRequest",
            "name": "TenantSecurityRequest",
            "summary": "Class\u0020used\u0020to\u0020communicate\u0020with\u0020the\u0020Tenant\u0020Security\u0020Proxy.",
            "url": "classes/IronCore-TenantSecurityRequest.html"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityRequest\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-TenantSecurityRequest.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityRequest\u003A\u003AmakeJsonRequest\u0028\u0029",
            "name": "makeJsonRequest",
            "summary": "Makes\u0020a\u0020POST\u0020request\u0020to\u0020a\u0020Tenant\u0020Security\u0020Proxy\u0020endpoint\u0020with\u0020the\u0020provided\u0020JSON\u0020payload.",
            "url": "classes/IronCore-TenantSecurityRequest.html#method_makeJsonRequest"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityRequest\u003A\u003AwrapKey\u0028\u0029",
            "name": "wrapKey",
            "summary": "Requests\u0020the\u0020TSP\u0020to\u0020generate\u0020a\u0020DEK\u0020and\u0020an\u0020EDEK.",
            "url": "classes/IronCore-TenantSecurityRequest.html#method_wrapKey"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityRequest\u003A\u003AbatchWrapKeys\u0028\u0029",
            "name": "batchWrapKeys",
            "summary": "Requests\u0020the\u0020TSP\u0020to\u0020generate\u0020multiple\u0020DEK\/EDEK\u0020pairs.",
            "url": "classes/IronCore-TenantSecurityRequest.html#method_batchWrapKeys"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityRequest\u003A\u003AunwrapKey\u0028\u0029",
            "name": "unwrapKey",
            "summary": "Requests\u0020the\u0020TSP\u0020to\u0020unwrap\u0020an\u0020EDEK.",
            "url": "classes/IronCore-TenantSecurityRequest.html#method_unwrapKey"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityRequest\u003A\u003AbatchUnwrapKeys\u0028\u0029",
            "name": "batchUnwrapKeys",
            "summary": "Requests\u0020the\u0020TSP\u0020to\u0020unwrap\u0020multiple\u0020EDEKs.",
            "url": "classes/IronCore-TenantSecurityRequest.html#method_batchUnwrapKeys"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityRequest\u003A\u003Arekey\u0028\u0029",
            "name": "rekey",
            "summary": "Requests\u0020the\u0020TSP\u0020to\u0020re\u002Dkey\u0020an\u0020EDEK.",
            "url": "classes/IronCore-TenantSecurityRequest.html#method_rekey"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityRequest\u003A\u003AlogSecurityEvent\u0028\u0029",
            "name": "logSecurityEvent",
            "summary": "Request\u0020to\u0020the\u0020security\u0020event\u0020endpoint\u0020with\u0020the\u0020provided\u0020event\u0020and\u0020metadata.",
            "url": "classes/IronCore-TenantSecurityRequest.html#method_logSecurityEvent"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityRequest\u003A\u003A\u0024tspAddress",
            "name": "tspAddress",
            "summary": "",
            "url": "classes/IronCore-TenantSecurityRequest.html#property_tspAddress"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityRequest\u003A\u003A\u0024apiKey",
            "name": "apiKey",
            "summary": "",
            "url": "classes/IronCore-TenantSecurityRequest.html#property_apiKey"
        },                {
            "fqsen": "\\IronCore\\TenantSecurityRequest\u003A\u003A\u0024ch",
            "name": "ch",
            "summary": "",
            "url": "classes/IronCore-TenantSecurityRequest.html#property_ch"
        },                {
            "fqsen": "\\IronCore\\Utils\\trimSlashes\u0028\u0029",
            "name": "trimSlashes",
            "summary": "Trims\u0020forward\u0020slashes\u0020\u0028\u0060\/\u0060\u0029\u0020from\u0020the\u0020front\u0020and\u0020end\u0020of\u0020a\u0020string.",
            "url": "namespaces/ironcore-utils.html#function_trimSlashes"
        },                {
            "fqsen": "\\IronCore\\V3HeaderSignature",
            "name": "V3HeaderSignature",
            "summary": "V3\u0020IronCore\u0020header\u0020signature",
            "url": "classes/IronCore-V3HeaderSignature.html"
        },                {
            "fqsen": "\\IronCore\\V3HeaderSignature\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/IronCore-V3HeaderSignature.html#method___construct"
        },                {
            "fqsen": "\\IronCore\\V3HeaderSignature\u003A\u003AfromBytes\u0028\u0029",
            "name": "fromBytes",
            "summary": "Constructs\u0020header\u0020signature\u0020from\u0020raw\u0020bytes.",
            "url": "classes/IronCore-V3HeaderSignature.html#method_fromBytes"
        },                {
            "fqsen": "\\IronCore\\V3HeaderSignature\u003A\u003AgetIv\u0028\u0029",
            "name": "getIv",
            "summary": "Gets\u0020the\u0020header\u0027s\u0020IV.",
            "url": "classes/IronCore-V3HeaderSignature.html#method_getIv"
        },                {
            "fqsen": "\\IronCore\\V3HeaderSignature\u003A\u003AgetSignatureBytes\u0028\u0029",
            "name": "getSignatureBytes",
            "summary": "Gets\u0020IronCore\u0020signature\u0020bytes.\u0020Consists\u0020of\u0020the\u0020IV\u0020concatenated\u0020with\u0020the\u0020GCM\u0020tag.",
            "url": "classes/IronCore-V3HeaderSignature.html#method_getSignatureBytes"
        },                {
            "fqsen": "\\IronCore\\V3HeaderSignature\u003A\u003A\u0024iv",
            "name": "iv",
            "summary": "",
            "url": "classes/IronCore-V3HeaderSignature.html#property_iv"
        },                {
            "fqsen": "\\IronCore\\V3HeaderSignature\u003A\u003A\u0024gcmTag",
            "name": "gcmTag",
            "summary": "",
            "url": "classes/IronCore-V3HeaderSignature.html#property_gcmTag"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\IronCore",
            "name": "IronCore",
            "summary": "",
            "url": "namespaces/ironcore.html"
        },                {
            "fqsen": "\\IronCore\\Crypto",
            "name": "Crypto",
            "summary": "",
            "url": "namespaces/ironcore-crypto.html"
        },                {
            "fqsen": "\\IronCore\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/ironcore-exception.html"
        },                {
            "fqsen": "\\Proto\\IronCoreLabs",
            "name": "IronCoreLabs",
            "summary": "",
            "url": "namespaces/proto-ironcorelabs.html"
        },                {
            "fqsen": "\\Proto",
            "name": "Proto",
            "summary": "",
            "url": "namespaces/proto.html"
        },                {
            "fqsen": "\\IronCore\\Rest",
            "name": "Rest",
            "summary": "",
            "url": "namespaces/ironcore-rest.html"
        },                {
            "fqsen": "\\IronCore\\SecurityEvents",
            "name": "SecurityEvents",
            "summary": "",
            "url": "namespaces/ironcore-securityevents.html"
        },                {
            "fqsen": "\\IronCore\\Utils",
            "name": "Utils",
            "summary": "",
            "url": "namespaces/ironcore-utils.html"
        }            ]
);
