<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: document_header.proto

namespace Proto\IronCoreLabs;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.ironcorelabs.cmk.DataControlPlatformHeader</code>
 */
class DataControlPlatformHeader extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string document_id = 1;</code>
     */
    protected $document_id = '';
    /**
     * Generated from protobuf field <code>uint64 segment_id = 2;</code>
     */
    protected $segment_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $document_id
     *     @type int|string $segment_id
     * }
     */
    public function __construct($data = NULL) {
        \Proto\IronCoreLabs\Metadata\DocumentHeader::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string document_id = 1;</code>
     * @return string
     */
    public function getDocumentId()
    {
        return $this->document_id;
    }

    /**
     * Generated from protobuf field <code>string document_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->document_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 segment_id = 2;</code>
     * @return int|string
     */
    public function getSegmentId()
    {
        return $this->segment_id;
    }

    /**
     * Generated from protobuf field <code>uint64 segment_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSegmentId($var)
    {
        GPBUtil::checkUint64($var);
        $this->segment_id = $var;

        return $this;
    }

}

