<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: document_header.proto

namespace Proto\IronCoreLabs;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.ironcorelabs.cmk.SaaSShieldHeader</code>
 */
class SaaSShieldHeader extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tenant_id = 1;</code>
     */
    protected $tenant_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tenant_id
     * }
     */
    public function __construct($data = NULL) {
        \Proto\IronCoreLabs\Metadata\DocumentHeader::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tenant_id = 1;</code>
     * @return string
     */
    public function getTenantId()
    {
        return $this->tenant_id;
    }

    /**
     * Generated from protobuf field <code>string tenant_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTenantId($var)
    {
        GPBUtil::checkString($var, True);
        $this->tenant_id = $var;

        return $this;
    }

}

