name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
env:
  MIN_COVERAGE: "80"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          tools: phpunit:9.5.10
          coverage: pcov
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-versions }}-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run test suite
        run: ./vendor/bin/phpunit --coverage-cobertura=cobertura.xml tests
      - name: Post code coverage to PR comment
        if: ${{ github.base_ref != '' }}
        uses: 5monkeys/cobertura-action@v12
        with:
          path: cobertura.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          only_changed_files: true
          show_line: true
          minimum_coverage: ${{ env.MIN_COVERAGE }}

  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-versions }}-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run lint
        run: composer run lint
